language: nodejs
node_js:
  - "10"

cache:
  directories:
      - "node_modules"

script:
  - npm run docs:build
  - npm run test
  - npm run coverage

deploy:
  - provider: script
    script: npx lerna publish -y from-git
    skip-cleanup: true
    on:
      tags: true
      branch: false
  - provider: pages
    skip-cleanup: true
    local_dir: docs/.vuepress/dist
    github-token: $GITHUB_TOKEN
    repo: reobervable/reobservable
    keep-history: true
    target-branch: master
    on:
      branch: master
